language: ruby
before_install:
  - gem update --system # necessary, see https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html
before_script:
  - gem install html-proofer
script:
  - bundle exec jekyll build
  - >-
    travis_retry htmlproofer ./_site
    --check-html
    --check-favicon
    --check-external-hash
    --check-opengraph
    --empty-alt-ignore
    --url-ignore $(paste -sd ',' < .ci/url_ignore)
