name: Links
on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - run: bundle exec jekyll build
      - uses: anishathalye/proof-html@v2
        with:
          directory: ./_site
          enforce_https: false
          tokens: |
            {"https://github.com": "${{ secrets.GITHUB_TOKEN }}"}
          ignore_url: |
            https://crates.io/
            http://dtrace.org/blogs/about/
            https://blogs.oracle.com/linux/strace-the-sysadmins-microscope-v2
            https://www.vmware.com/
            https://fossbytes.com/enable-full-disk-encryption-windows-10/
            http://debian.xfree.com.ar/debian-cd/current/amd64/iso-cd/
            https://www.springboard.com/blog/data-science/free-public-data-sets-data-science-project/
            https://ucr.fbi.gov/crime-in-the-u.s/2016/crime-in-the-u.s.-2016/topic-pages/tables/table-1
            https://www.autohotkey.com/
            https://rsync.samba.org/
            https://fidoalliance.org/
            https://wiki.mozilla.org/Security/Server_Side_TLS
            https://undo.io/resources/reverse-debugging-whitepaper/
            https://www.virtualbox.org/
            https://pdw.ex-parrot.com/iftop/
          ignore_url_re: |
            ^http://www.brendangregg.com/
            ^https:\/\/help\.github\.com\/
            ^https:\/\/linux\.die\.net\/man\/
            ^https:\/\/www\.reddit\.com\/
            ^https:\/\/stackoverflow\.com\/
            ^https:\/\/.*\.stackoverflow\.com\/
            ^https:\/\/.*\.stackexchange\.com\/
          swap_urls: |
            {"^(https://github\\.com/.*)#.*$": "\\1"}
